### PR TITLE
Ran npm audit fix (4334 of 4407 fixed)

### PR DESCRIPTION
**Pull request by null267**
PASS src/tests/index.test.js (13.179 s)
  the tooltip component
    √ renders as expected (22 ms)
    √ shows itself upon parent mouse enter (11 ms)
    √ hides itself upon parent mouse leave (5 ms)
    √ hides itself upon mouse enter (7 ms)
    √ shows itself by default if sticky is enabled (5 ms)
    on scroll
      √ does nothing if tooltip is hidden (36 ms)
      √ redraws if tooltip is visible (5 ms)
    API contract
      √ declares the expected required props (1 ms)
      √ declares the expected propTypes (1 ms)
      √ declares the expected defaultProps

Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   5 passed, 5 total
Time:        18.481 s
Ran all test suites matching /src\\/i.

### CODE REVIEW

**Comment by orzechowskid** [comment]
looks like `rollup-plugin-postcss` could have been updated - why did you decide to skip it?

**Comment by null267** [comment]
I've been trying to update it manually, and it hasn't been working.  Still
fiddling with it.

**Comment by null267** [comment]
Also, what I'm seeing is that postcss is the vulnerability issue as a
dependency of rollup-plugin-postcss.

**Comment by null267** [comment]
Ok... npm audit is telling me about a vulnerability that was fixed in 8.2,
even though the version specified in package.json is >=8.3.  What the hell.

**Comment by null267** [comment]
I checked npm on rollup-plugin-postcss, and it says that 3.0 and above
introduce a breaking change that makes them incompatible with versions of
rollup under 2.0.  Npm install seems to default to 1.3.2; perhaps later
versions results in some other incompatibility?

**Pull request merged**
